namespace LetWeCook.Common.Enums
{
    public enum ErrorCode
    {
        UserNotFound,
        EmailConfirmationFailed,
        EmailConfirmationException,
        MediaUrlCreationFailed,
        MediaUrlDeletionFailed,
        MediaUrlSaveFailed,
        MediaUrlRetrievalFailed,
        MediaUrlNotFound,
        CloudinaryImageUploadFailed,
        IngredientCreationFailed,
        IngredientRetrievalFailed,
        IngredientNotFound,
        IngredientSectionRetrievalFailed,
        RecipeRetrievalFailed,
        RecipeCreationFailed,
        RecipeNotFound,
        UserProfileRetrievalFailed,
        UserProfileCreationFailed,
        UserProfileSaveFailed,
        UserProfileNotFound,
        DatabaseSaveFailed,
        InvalidBase64Image,
        InvalidMediaUrl,
        UnexpectedError,
        None
    }
}
